version: "3.7"
services:
  app:
    build:
      args:
        user: eduuser-2
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: educontestimage-2
    container_name: educontestcontainer-2
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - edunetwork
  db:
    image: mysql:8.0
    container_name: educontestdbcontainer-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - edunetwork
  nginx:
    image: nginx:alpine
    container_name: educontestcontainer-2
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - edunetwork
networks:
  edunetwork:
    driver: bridge